update trex

diff --git a/integration-tests/rh-trex-test.yaml b/integration-tests/rh-trex-test.yaml
--- a/integration-tests/rh-trex-test.yaml
+++ b/integration-tests/rh-trex-test.yaml
@@ -12,14 +12,6 @@ spec:
       name: SNAPSHOT
       default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
       type: string
-    - description: 'Namespace where the application is running'
-      name: NAMESPACE
-      default: "default"
-      type: string
-    - description: 'Application endpoint port'
-      name: PORT
-      default: ""
-      type: string
     - description: 'Horreum Test Name'
       name: HR_TEST_NAME
       default: ""
@@ -27,6 +19,10 @@ spec:
     - description: 'Horreum regression variable'
       name: HR_REG_VAR
       default: ""
+      type: string        
+    - description: 'Horreum url'
+      name: HORREUM_URI
+      default: "https://horreum.corp.redhat.com"
       type: string        
   tasks:
     - name: provision-env
@@ -49,11 +45,9 @@ spec:
                 value: "$(context.pipelineRun.uid)"
             script: |
               #!/bin/bash
-              oc get secret horreum
               set -ex
               set -o pipefail
-              oc get secret ocm
-              
+      
               cat <<EOF > space_request.yaml
               apiVersion: toolchain.dev.openshift.com/v1alpha1
               kind: SpaceRequest
@@ -80,11 +74,7 @@ spec:
     - name: extract-secrets
       taskSpec:
         results:
-          - name: HORREUM_PASSWORD
-            type: string
-          - name: HORREUM_URI
-            type: string
-          - name: HORREUM_USER
+          - name: HORREUM_API_KEY
             type: string
           - name: HORREUM_COFIG_SET
             type: string                       
@@ -94,44 +84,24 @@ spec:
             script: |
               #!/bin/bash
               horreum_sec_set='true'
-              horreum_password=''
-              horreum_uri=''
-              horreum_user=''
+              horreum_api_key=''
               oc get secret horreum
               if [ $? -ne 0 ]; then
                 horreum_sec_set='false'
               else
-                horreum_password=$(oc get secret horreum -o jsonpath='{.data.horreum_password}' | base64 --decode)
-                horreum_uri=$(oc get secret horreum -o jsonpath='{.data.horreum_uri}' | base64 --decode)
-                horreum_user=$(oc get secret horreum -o jsonpath='{.data.horreum_user}' | base64 --decode)
+                horreum_api_key=$(oc get secret horreum -o jsonpath='{.data.horreum_api_key}' | base64 --decode)
               fi
-              echo -n "${horreum_password}" | tee $(results.HORREUM_PASSWORD.path)
-              echo -n "${horreum_uri}" | tee $(results.HORREUM_URI.path)
-              echo -n "${horreum_user}" | tee $(results.HORREUM_USER.path)                
-              echo -n "${horreum_sec_set}" | tee $(results.HORREUM_COFIG_SET.path)            
+              echo -n "${horreum_api_key}" | tee $(results.HORREUM_API_KEY.path)
+              echo -n "${horreum_sec_set}" | tee $(results.HORREUM_COFIG_SET.path)                   
     - name: deploy-app
-      runAfter: 
-        - provision-env
-        - extract-secrets
+      runAfter: [provision-env]
       params:
         - name: SNAPSHOT
           value: $(params.SNAPSHOT)
-        - name: NAMESPACE
-          value: $(params.NAMESPACE)
-        - name: PORT
-          value: $(params.PORT)
         - name: HR_TEST_NAME
           value: $(params.HR_TEST_NAME)          
         - name: HR_REG_VAR
           value: $(params.HR_REG_VAR)
-        - name: HORREUM_COFIG_SET
-          value: $(tasks.extract-secrets.results.HORREUM_COFIG_SET)
-        - name: HORREUM_PASSWORD
-          value: $(tasks.extract-secrets.results.HORREUM_PASSWORD)
-        - name: HORREUM_URI
-          value: $(tasks.extract-secrets.results.HORREUM_URI)
-        - name: HORREUM_USER
-          value: $(tasks.extract-secrets.results.HORREUM_USER)                                        
       taskSpec:
         params:
           - name: SNAPSHOT
@@ -145,15 +115,7 @@ spec:
           - name: HR_TEST_NAME
             description: 'Horreum Test Name'            
           - name: HR_REG_VAR
-            description: 'Horreum regression variable'
-          - name: HORREUM_COFIG_SET
-            description: 'Horreum regression variable'
-          - name: HORREUM_PASSWORD
-            description: 'Horreum regression variable'
-          - name: HORREUM_URI
-            description: 'Horreum regression variable'
-          - name: HORREUM_USER
-            description: 'Horreum regression variable'                                                 
+            description: 'Horreum regression variable'            
         results:
           - name: APP_URL
             description: APP URL
@@ -168,10 +130,6 @@ spec:
           env:
             - name: SNAPSHOT
               value: $(params.SNAPSHOT)
-            - name: NAMESPACE
-              value: $(params.NAMESPACE)
-            - name: PORT
-              value: $(params.PORT)               
             - name: KUBECONFIG_VALUE
               valueFrom:
                 secretKeyRef:
@@ -190,18 +148,146 @@ spec:
           script: |
             #!/usr/bin/env bash
             cat <<< "$KUBECONFIG_VALUE" > /tmp/cfg
+            dnf -y install jq git
             export KUBECONFIG=/tmp/cfg
-            oc get secret
-            echo $(params.HORREUM_COFIG_SET)
+
+            # Get the route for the application endpoint
+            COMPONENT_NAME=$(echo -n ${SNAPSHOT} | jq -r .components[0].name)
+            # The --insecure-skip-tls-verify option is added for local testing
+            # when the clusters only have self-signed certificates.
+            # This option should not be used in production.
+
+            TARGET_COMPONENT_NAME="/tmp/rh-trex"
+            REPO_URL=$(echo $SNAPSHOT | jq -r '.components[] | .source.git.url')
+            REPO_COMMIT=$(echo $SNAPSHOT | jq -r '.components[] | .source.git.revision')
+            REPO_IMG=$(echo $SNAPSHOT | jq -r '.components[] | .containerImage')
+            git clone $REPO_URL $TARGET_COMPONENT_NAME
+            cd $TARGET_COMPONENT_NAME
+            git checkout $REPO_COMMIT
+            rev=$(echo ${REPO_IMG#*/})
+            image_reg=$(echo ${REPO_IMG%%/*})
+            image_tag=$(echo ${rev#*:})
+            image_rep=$(echo ${rev%:*})
+            mkdir -p /tmp/templates/
+            for i in $(ls templates/*yml); do j=${i#*/}; outf=${j%.*};oc process --kubeconfig /tmp/cfg --filename="$i" --local="true" --ignore-unknown-parameters="true" --param="ENVIRONMENT"=development --param="GLOG_V"=10  --param="DATABASE_HOST"=trex-db.$(oc project --short) --param="DATABASE_NAME"=rhtrex  --param="DATABASE_PASSWORD"=foobar-bizz-buzz  --param="DATABASE_PORT"=5432 --param="DATABASE_USER"=trex  --param="DATABASE_SSLMODE"=disable --param="ENABLE_SENTRY"=false --param="SENTRY_KEY"=TODO --param="JWKS_URL"=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs  --param="OCM_SERVICE_CLIENT_ID"=${CLIENT_ID} --param="OCM_SERVICE_CLIENT_SECRET"=${CLIENT_SEC}  --param="OCM_BASE_URL"=https://api.integration.openshift.com --param="IMAGE_REGISTRY="$image_reg --param="IMAGE_REPOSITORY="$image_rep --param="IMAGE_TAG="$image_tag  > /tmp/templates/${outf}.json; done
+            oc apply --kubeconfig /tmp/cfg  -f /tmp/templates/db-template.json
+            sleep 60
+            oc apply --kubeconfig /tmp/cfg  -f /tmp/templates/secrets-template.json
+            oc apply --kubeconfig /tmp/cfg  -f /tmp/templates/service-template.json
+            sleep 60
+            oc get --kubeconfig /tmp/cfg all
+            oc get --kubeconfig /tmp/cfg events
+            oc describe --kubeconfig /tmp/cfg pod -l app=trex
+            oc logs --kubeconfig /tmp/cfg -l app=trex
+
+            if [ -z $(params.HR_TEST_NAME) ]
+            then
+              echo '$(params.SNAPSHOT)'|jq -r .components[].name |  tr -d '\n\t' | tee $(results.test_name.path)
+            else
+              echo -n  '$(params.HR_TEST_NAME)' | tee $(results.test_name.path)
+            fi            
+            
+            if [ -z $(params.HR_REG_VAR) ]
+            then
+              echo -n 'iteration_duration' | tee $(results.reg_var.path)
+            else
+              echo -n '$(params.HR_REG_VAR)' | tee $(results.reg_var.path)
+            fi             
+    - name: perf-benchmark 
+      params:
+        - name: test_name
+          value: $(tasks.deploy-app.results.test_name)
+        - name: reg_var
+          value: $(tasks.deploy-app.results.reg_var)
+        - name: HORREUM_COFIG_SET
+          value: $(tasks.extract-secrets.results.HORREUM_COFIG_SET)
+        - name: HORREUM_API_KEY
+          value: $(tasks.extract-secrets.results.HORREUM_PASSWORD)
+        - name: HORREUM_URI
+          value: $(params.HORREUM_URI)
+      taskSpec:
+        params:
+          - name: test_name
+          - name: reg_var
+          - name: HORREUM_COFIG_SET
+          - name: HORREUM_API_KEY
+          - name: HORREUM_URI
+        sidecars:
+        - name: port-forward
+          image: registry.redhat.io/openshift4/ose-cli:latest
+          env:       
+            - name: KUBECONFIG_VALUE
+              valueFrom:
+                secretKeyRef:
+                  name: "$(tasks.provision-env.results.secretRef)"
+                  key: kubeconfig          
+          ports:
+            - containerPort: 8080
+          script: |
+            #!/usr/bin/env bash
+            cat <<< "$KUBECONFIG_VALUE" > /tmp/cfg
+            export KUBECONFIG=/tmp/cfg
+            oc port-forward --kubeconfig /tmp/cfg svc/trex 8080:8000                        
+        steps:
+        - image: grafana/k6
+          name: run-perf
+          env:
+            - name: OCM_TOKEN
+              valueFrom:
+                secretKeyRef:
+                  name: ocm
+                  key: ocmtoken          
+          script: |
+            #!/usr/bin/env sh
+            wget -O /tmp/ocm https://github.com/openshift-online/ocm-cli/releases/download/v0.1.65/ocm-linux-amd64
+            chmod +x /tmp/ocm
+            /tmp/ocm login --token=${OCM_TOKEN} --url=https://127.0.0.1:8080 --debug
+            export BASE_URL=https://127.0.0.1:8080
+            wget -O /tmp/script.js https://raw.githubusercontent.com/yogananth-subramanian/testrepo/refs/heads/main/integration-tests/rhtap-perf-k6-test.js
+            echo -n `/tmp/ocm token`>/tmp/token
+            k6 run /tmp/script.js
+            cat /workspace/output.json
+        - image: quay.io/yogananth_subramanian/curl-yq-jq
+          name: check-regression
+          script: |
+            set -x
             horreum_sec_set=$(params.HORREUM_COFIG_SET)
             if [ ${horreum_sec_set} == 'false' ]; then
-              echo "horreum config not set"
+              echo "Horreum config not set"
             else
-              echo "uploading to horreum"
-              echo $(params.HORREUM_PASSWORD)
-              echo $(params.HORREUM_URI)
-              echo $(params.HORREUM_USER)
-            fi    
-            echo "====================="
-
-            
+              echo "Transform result to json format"
+              cat /workspace/output.json
+              test_name=$(params.test_name)
+              reg_var=$(params.reg_var)
+              KEYCLOAK_URI=$(curl -s -k -X GET  ${HORREUM_URI}/api/config/keycloak|jq -r .url)
+              curl -k -s -v ${HORREUM_URI}'/api/run/data?start=$.startTime&stop=$.endTime&test='$test_name -X POST -H 'Content-Type: application/json' -H 'X-Horreum-API-Key: '${HORREUM_API_KEY}  -d @/workspace/output.json
+              testid=$(curl -s -k -X GET  ${HORREUM_URI}'/api/test/byName/'$test_name -H 'X-Horreum-API-Key: '${HORREUM_API_KEY} |jq -r .id)
+              varid=$(curl -s -k -X GET  ${HORREUM_URI}'/api/alerting/variables?test='$testid -H 'X-Horreum-API-Key: '${HORREUM_API_KEY}|jq -r --arg regvar "$reg_var" '.[] | select(.name==$regvar)| .id ')
+              changes=`curl -s -k -X GET ${HORREUM_URI}'/api/alerting/changes?var='$varid  -H 'X-Horreum-API-Key: '${HORREUM_API_KEY}|jq  '.| length'`
+              if [ -z  $changes ] || [ $changes -gt 0  ] ;then echo "Regression check failed";exit 1;fi                  
+            fi 
+      runAfter:
+        - deploy-app
+        - extract-secrets    
+  finally:
+    - name: cleanup  
+      params:
+        - name: aggregateTasksStatus
+          value: "$(tasks.status)"
+      taskSpec:
+        results:
+          - name: TEST_OUTPUT
+        params:
+          - name: aggregateTasksStatus
+        steps:
+        - image: quay.io/yogananth_subramanian/curl-yq-jq  
+          name: step1
+          script: |
+            RESULT="SUCCESS"
+            if [ $(params.aggregateTasksStatus) == "Failed" ]
+            then
+              RESULT="FAILURE"
+            fi
+            TEST_OUTPUT=$(jq -rc --arg date $(date +%s) --arg RESULT "${RESULT}" --null-input \
+            '{result: $RESULT, timestamp: $date, failures: 0, successes: 0, warnings: 0}')
+            echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)
